export const testClassPrefix = 'T-';

export const testClasses = {
  fileTreeItems: testClassPrefix + 'file-tree-item',
  tagTreeItem: testClassPrefix + 'tag-tree-item',
  bookItems: testClassPrefix + 'book-item',
  tab: testClassPrefix + 'view-tab',
  label: testClassPrefix + 'label',
  openedTab: testClassPrefix + 'view-tab-opened',
  editorTitle: testClassPrefix + 'editor-title',
  editorAuthor: testClassPrefix + 'editor-author',
  editorYear: testClassPrefix + 'editor-year',
  editorIsbn: testClassPrefix + 'editor-isbn',
  editorFilename: testClassPrefix + 'editor-filename',
  editorMarkdown: testClassPrefix + 'editor-markdown',
  editorTag: testClassPrefix + 'editor-tag',
  editorAddTag: testClassPrefix + 'editor-add-tag',
  editorStar: testClassPrefix + 'editor-star',
  editorStarFilled: testClassPrefix + 'editor-star-filled',
  editorStarHalf: testClassPrefix + 'editor-star-half',
  editorStarEmpty: testClassPrefix + 'editor-star-empty',
  editorDateFrom: testClassPrefix + 'editor-date-from',
  editorDateTo: testClassPrefix + 'editor-date-to',
  editorDateAdd: testClassPrefix + 'editor-date-add',
  editorDateRemove: testClassPrefix + 'editor-date-remove',
  editorCalendarYearInput: testClassPrefix + 'calendar-year-input',
  editorCalendarDay: testClassPrefix + 'calendar-day',
  editorCalendarMonthSelectorButton: testClassPrefix + 'calendar-year-month-selector-button',
  editorCalendarMonthSelectorMonth: testClassPrefix + 'calendar-month-selector-month',
  menuHome: testClassPrefix + 'menu-home',
  menuSettings: testClassPrefix + 'menu-settings',
  menuAddBook: testClassPrefix + 'menu-add-book',
  modalClose: testClassPrefix + 'modal-close',
  settingsChangeRootPath: testClassPrefix + 'settings-change-root-path',
};
