// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DateRead } from './DateRead';

export type AttrValue =
  | string
  | null
  | Array<string>
  | null
  | Array<DateRead>
  | null
  | bigint
  | null
  | number
  | null;
