// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DateRead } from './DateRead';

export type AttrValue =
  | { type: 'Text'; value: string }
  | { type: 'TextCollection'; value: Array<string> }
  | { type: 'DatesPairCollection'; value: Array<DateRead> }
  | { type: 'Number'; value: number }
  | { type: 'Date'; value: string }
  | { type: 'DateCollection'; value: Array<string> }
  | { type: 'Image'; value: string };
