// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DateRead } from './DateRead';

export type AttrValue =
  | { Text: string }
  | { TextCollection: Array<string> }
  | { DatesPairCollection: Array<DateRead> }
  | { Number: number }
  | { Date: string }
  | { DateCollection: Array<string> }
  | { Image: string };
