// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BookFromDb } from './BookFromDb';
import type { ErrorFromRust } from './ErrorFromRust';
import type { Schema } from './Schema';

export type BookReadResult = {
  book: BookFromDb;
  parsing_error: ErrorFromRust | null;
  schema: Schema;
};
