// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BookFromDb } from './BookFromDb';
import type { Schema } from './Schema';

export type BookListGetResult = { schema: Schema; books: Array<BookFromDb> };
