// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SchemaItem } from './SchemaItem';

export type DefaultSchema = { name: string; description: string; schema_items: Array<SchemaItem> };
