// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorActionCode } from './ErrorActionCode';

export type ErrorFromRust = {
  isError: boolean;
  title: string;
  info?: string;
  rawError?: string;
  subErrors: Array<ErrorFromRust>;
  actionCode?: ErrorActionCode;
  actionLabel?: string;
};
