// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BookFromDb } from './BookFromDb';
import type { ErrorFromRust } from './ErrorFromRust';
import type { FolderEventEmit } from './FolderEventEmit';

export type IPCEmitEvent =
  | { type: 'FileRemove'; data: string }
  | { type: 'FileAdd'; data: BookFromDb }
  | { type: 'FileUpdate'; data: BookFromDb }
  | { type: 'FolderRemove'; data: FolderEventEmit }
  | { type: 'FolderAdd'; data: FolderEventEmit }
  | { type: 'ErrorHappened'; data: ErrorFromRust };
