// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BookListGetResult } from './BookListGetResult';
import type { BookReadResult } from './BookReadResult';
import type { BookSaveResult } from './BookSaveResult';
import type { DefaultSchema } from './DefaultSchema';
import type { ErrorFromRust } from './ErrorFromRust';
import type { Schema } from './Schema';
import type { SchemaLoadList } from './SchemaLoadList';

export type IPCResponces = {
  c_init_once: { Ok: boolean } | { Err: ErrorFromRust };
  c_prepare_cache: { Ok: boolean } | { Err: ErrorFromRust };
  c_watch_path: { Ok: boolean } | { Err: ErrorFromRust };
  c_get_files_path: { Ok: BookListGetResult } | { Err: ErrorFromRust };
  c_get_all_tags: { Ok: Array<string> } | { Err: ErrorFromRust };
  c_get_all_folders: { Ok: Array<string> } | { Err: ErrorFromRust };
  c_read_file_by_path: { Ok: BookReadResult } | { Err: ErrorFromRust };
  c_load_schemas: { Ok: SchemaLoadList } | { Err: ErrorFromRust };
  c_get_schemas: { Ok: Array<Schema> } | { Err: ErrorFromRust };
  c_load_schema: { Ok: Schema } | { Err: ErrorFromRust };
  c_save_schema: { Ok: Schema } | { Err: ErrorFromRust };
  c_save_file: { Ok: BookSaveResult } | { Err: ErrorFromRust };
  c_get_default_schemas: { Ok: Array<DefaultSchema> } | { Err: ErrorFromRust };
};
