// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InputSize } from './InputSize';
import type { NumberStyle } from './NumberStyle';
import type { SettingsTypeNumber } from './SettingsTypeNumber';

export type NumberSettings = {
  settingsType: SettingsTypeNumber;
  displayName?: string;
  size?: InputSize;
  min?: number;
  max?: number;
  style?: NumberStyle;
  decimalPlaces?: number;
};
