// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SchemaAttrType } from './SchemaAttrType';

export type SchemaItem = { name: string; value: SchemaAttrType };
