// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SchemaAttrKey } from './SchemaAttrKey';

export type SchemaItem = { name: string; value: SchemaAttrKey };
