// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SchemaItem } from './SchemaItem';

export type Schema = {
  name: string;
  version: string;
  icon: string | null;
  items: Array<SchemaItem>;
  internal_path: string;
  internal_name: string;
};
