// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TableNames = { table_prefix: string; files_table: string; folders_table: string };
