// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InputSize } from './InputSize';
import type { SettingsTypeText } from './SettingsTypeText';
import type { TextFont } from './TextFont';
import type { TextTheme } from './TextTheme';
import type { TextWeight } from './TextWeight';

export type TextSettings = {
  settingsType: SettingsTypeText;
  displayName?: string;
  size?: InputSize;
  font?: TextFont;
  weight?: TextWeight;
  theme?: TextTheme;
  isMultiline?: boolean;
};
