// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InputSize } from './InputSize';
import type { SettingsTypeTextCollection } from './SettingsTypeTextCollection';
import type { TextFont } from './TextFont';
import type { TextWeight } from './TextWeight';

export type TextCollectionSettings = {
  settingsType: SettingsTypeTextCollection;
  displayName?: string;
  size?: InputSize;
  font?: TextFont;
  weight?: TextWeight;
  prefix?: string;
};
